OPENAI_API_KEY: ENV_OPENAI_API_KEY
OPENAI_ORG_ID: ENV_OPENAI_ORG_ID
PINECONE_API_KEY: ENV_PINECONE_API_KEY
PINECONE_INDEX_NAME: builtenv
PINECONE_ENV: aws
GRAPHRAG_LLM_API_BASE: null
GRAPHRAG_EMBEDDING_MODEL: text-embedding-3-small
GRAPHRAG_EMBEDDING_API_BASE: null
GRAPHRAG_CLAIM_EXTRACTION_ENABLED: False
SERVICE_ID: sk-test
INPUT_DIR: "./legalRAG/output/"
COMMUNITY_LEVEL: 2
RESPONSE_TYPE: "single paragraph"